// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCYvO1FQH1oc3sqrkYFG6qzFxN7WFGt7Ko',
//     appId: '1:28886943657:web:c51758b590e220019ca6b8',
//     messagingSenderId: '28886943657',
//     projectId: 'ewa-ecommerce-fb03b',
//     authDomain: 'ewa-ecommerce-fb03b.firebaseapp.com',
//     storageBucket: 'ewa-ecommerce-fb03b.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCH31BI1oKbB7XF_1I98NmXf9xa86yP004',
//     appId: '1:28886943657:android:0572544602b174b39ca6b8',
//     messagingSenderId: '28886943657',
//     projectId: 'ewa-ecommerce-fb03b',
//     storageBucket: 'ewa-ecommerce-fb03b.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC1VtpeLK9x4RYSqqy6ljzA7vhUtWB9pSg',
//     appId: '1:28886943657:ios:84ba7d497d46a1679ca6b8',
//     messagingSenderId: '28886943657',
//     projectId: 'ewa-ecommerce-fb03b',
//     storageBucket: 'ewa-ecommerce-fb03b.firebasestorage.app',
//     iosBundleId: 'com.example.ewaCommerce',
//   );
// }
